const fs=require('fs'); const vm=require('vm');
function assert(c,m){if(!c){throw new Error(m)}}
const page=fs.readFileSync('harborhack-2026/index.html','utf8');
const home=fs.readFileSync('index.html','utf8');
assert(page.includes('HarborHack 2026'),'route renders event name');
assert(fs.existsSync('harborhack-2026/index.html'),'direct route file exists');
assert(home.includes('/harborhack-2026'),'homepage links to HarborHack');
assert(home.includes('Building Charleston into a recognized tech hub'),'existing homepage content remains');
assert(page.includes('https://harborhack-2026.devpost.com/'),'registration destination');
assert(page.includes('October 23–25, 2026'),'confirmed event dates');
assert(page.includes('College of Charleston'),'confirmed venue');
assert(page.includes('No prerecorded project video is required'),'video requirement copy');
assert(page.includes('Every HarborHack team works alongside a persistent AI agent as part of the team'),'agent teammate copy');
assert(!page.includes('ROOK'),'no ROOK branding remains');
assert(!page.includes('fake AI chat'),'no fake agent UI');
assert((page.match(/rel="noopener noreferrer"/g)||[]).length>=0,'safe attrs supported by JS');
assert(!page.includes('mission-workbook'),'mission workbook removed');
assert(!page.includes('Create a mission brief'),'mission brief action removed');
assert(!page.includes('signature-visual'),'shared progress graphic removed');
const app=fs.readFileSync('assets/js/harborhack/app.js','utf8');
assert(!app.includes('initWorksheet'),'mission worksheet behavior removed');
assert(!app.includes('hh26-mission'),'mission worksheet storage removed');
let sandbox={window:{},document:{addEventListener(){},querySelector(){return null},querySelectorAll(){return[]}}};
vm.runInNewContext(fs.readFileSync('assets/js/harborhack/config.js','utf8'),sandbox);
vm.runInNewContext(fs.readFileSync('assets/js/harborhack/app.js','utf8'),sandbox);
assert(sandbox.window.HARBORHACK_2026_CONFIG.eventName==='HarborHack 2026','config value appears');
console.log('HarborHack static tests passed');
