const fs=require('fs'); const vm=require('vm');
function assert(c,m){if(!c){throw new Error(m)}}
const page=fs.readFileSync('harborhack-2026/index.html','utf8');
const home=fs.readFileSync('index.html','utf8');
assert(page.includes('HarborHack 2026'),'route renders event name');
assert(fs.existsSync('harborhack-2026/index.html'),'direct route file exists');
assert(home.includes('/harborhack-2026'),'homepage links to HarborHack');
assert(home.includes('Building Charleston into a recognized tech hub'),'existing homepage content remains');
assert(page.includes('Registration link coming soon'),'missing registration fallback');
assert(page.includes('Schedule to be announced'),'missing schedule fallback');
assert(page.includes('No prerecorded project video is required'),'video requirement copy');
assert(page.includes('Every HarborHack team receives the same persistent synthetic engineering teammate: ROOK'),'ROOK common teammate copy');
assert(page.includes('not inside the CharlestonHacks website'),'ROOK boundary copy');
assert(!page.includes('fake AI chat'),'no fake ROOK UI');
assert((page.match(/rel="noopener noreferrer"/g)||[]).length>=0,'safe attrs supported by JS');
assert(fs.readFileSync('assets/js/harborhack/app.js','utf8').includes('localStorage'),'local checklist/worksheet state');
const app=fs.readFileSync('assets/js/harborhack/app.js','utf8');
assert(!app.includes('fetch('),'mission worksheet is not transmitted via fetch');
assert(!app.includes('XMLHttpRequest'),'mission worksheet is not transmitted via XHR');
let sandbox={window:{},document:{addEventListener(){},querySelector(){return null},querySelectorAll(){return[]}}};
vm.runInNewContext(fs.readFileSync('assets/js/harborhack/config.js','utf8'),sandbox);
vm.runInNewContext(fs.readFileSync('assets/js/harborhack/app.js','utf8'),sandbox);
assert(sandbox.window.HARBORHACK_2026_CONFIG.eventName==='HarborHack 2026','config value appears');
const r=sandbox.window.harborhackNextAction.recommend;
assert(r({},new Date('2026-01-01'),{...sandbox.window.HARBORHACK_2026_CONFIG,eventStartDate:'2026-07-01',eventEndDate:'2026-07-03',registrationUrl:'https://example.com'})[0].includes('Register'),'pre-event next action');
assert(r({done:{registered:true,community:true,conduct:true,rook:true,localModel:true}},new Date('2026-07-02'),{...sandbox.window.HARBORHACK_2026_CONFIG,eventStartDate:'2026-07-01',eventEndDate:'2026-07-03',submissionDeadline:'2026-07-02T23:00:00'})[0].includes('Open ROOK'),'event next action');
assert(r({done:{registered:true,community:true,conduct:true,rook:true,localModel:true}},new Date('2026-07-03T01:00:00'),{...sandbox.window.HARBORHACK_2026_CONFIG,eventStartDate:'2026-07-01',eventEndDate:'2026-07-04',submissionDeadline:'2026-07-02T23:00:00'})[0].includes('Prepare the live presentation'),'submission/presentation next action');
assert(r({done:{registered:true,community:true,conduct:true,rook:true,localModel:true}},new Date('2026-07-05'),{...sandbox.window.HARBORHACK_2026_CONFIG,eventStartDate:'2026-07-01',eventEndDate:'2026-07-04'})[0].includes('Continue'),'post-event next action');
console.log('HarborHack static tests passed');
