const fs=require('fs'); const vm=require('vm');
function assert(c,m){if(!c){throw new Error(m)}}
const page=fs.readFileSync('harborhack-2026/index.html','utf8');
const home=fs.readFileSync('index.html','utf8');
assert(page.includes('HarborHack 2026'),'route renders event name');
assert(fs.existsSync('harborhack-2026/index.html'),'direct route file exists');
assert(home.includes('/harborhack-2026'),'homepage links to HarborHack');
assert(home.includes('Building Charleston into a recognized tech hub'),'existing homepage content remains');
const configSource=fs.readFileSync('assets/js/harborhack/config.js','utf8');
assert(configSource.includes('https://harborhack-2026.devpost.com/'),'registration destination');
assert(configSource.includes('October 23–25, 2026'),'confirmed event dates');
assert(configSource.includes('College of Charleston'),'confirmed venue');
assert(page.includes('No prerecorded project video is required'),'video requirement copy');
assert(page.includes('every team builds a project with an AI agent as a teammate'),'agent teammate copy');
assert(!page.includes('ROOK'),'no ROOK branding remains');
assert(!page.includes('fake AI chat'),'no fake agent UI');
assert((page.match(/rel="noopener noreferrer"/g)||[]).length>=0,'safe attrs supported by JS');
assert(!page.includes('mission-workbook'),'mission workbook removed');
assert(!page.includes('Create a mission brief'),'mission brief action removed');
assert(!page.includes('signature-visual'),'shared progress graphic removed');
assert(!page.includes('id="event-day"'),'event-day dashboard removed');
assert(!page.includes('Rehearsal timer'),'rehearsal timer removed');
assert(!page.includes('id="rules"'),'draft rules removed');
assert(!page.includes('id="resources"'),'resource directory removed');
assert((page.match(/<nav[^>]*>[\s\S]*?<\/nav>/)||[''])[0].match(/href=/g).length===6,'navigation has brand and five page links');
['overview','how-it-works','schedule','faq','register'].forEach(id=>assert(page.includes(`id="${id}"`),`navigation target ${id} exists`));
assert((page.match(/data-registration-link/g)||[]).length===2,'registration CTAs appear twice');
['calendar-google','calendar-ics','calendar-apple','calendar-outlook'].forEach(id=>assert(page.includes(`id="${id}"`),`calendar control ${id} appears`));
assert(/id="calendar-google"[^>]*target="_blank"[^>]*rel="noopener noreferrer"/.test(page),'Google Calendar uses safe external-link attributes');
const retiredChallengeTerms=[['Challenge','2'].join(' '),['both','challenges'].join(' '),['one or both','challenges'].join(' ')];
retiredChallengeTerms.forEach(term=>assert(!page.toLowerCase().includes(term.toLowerCase()),`${term} removed from page`));
const app=fs.readFileSync('assets/js/harborhack/app.js','utf8');
assert(!app.includes('initWorksheet'),'mission worksheet behavior removed');
assert(!app.includes('hh26-mission'),'mission worksheet storage removed');
assert(!app.includes('initResources'),'resource behavior removed');
assert(!app.includes('initTimer'),'timer behavior removed');
assert(!app.includes('initEventDay'),'event-day behavior removed');
assert(app.includes('function initCalendar()'),'calendar behavior restored');
assert(app.includes("new Blob([ics()], { type: 'text/calendar' })"),'calendar download uses text/calendar MIME type');
assert(app.includes("anchor.download = 'harborhack-2026.ics'"),'calendar download has an .ics filename');
let sandbox={window:{},document:{addEventListener(){},querySelector(){return null},querySelectorAll(){return[]}}};
vm.runInNewContext(configSource,sandbox);
vm.runInNewContext(fs.readFileSync('assets/js/harborhack/app.js','utf8'),sandbox);
assert(sandbox.window.HARBORHACK_2026_CONFIG.eventName==='HarborHack 2026','config value appears');
assert(sandbox.window.HARBORHACK_2026_CONFIG.registrationUrl==='https://harborhack-2026.devpost.com/','registration URL remains exact');

const calendarSandbox={window:{HARBORHACK_2026_CONFIG:sandbox.window.HARBORHACK_2026_CONFIG},document:{addEventListener(){},querySelector(){return null},querySelectorAll(){return[]}},URLSearchParams,Blob,URL,setTimeout};
const calendarTestSource=app.replace("document.addEventListener('DOMContentLoaded'",'window.__calendarTest={ics,calendarData,icsDate}; document.addEventListener(\'DOMContentLoaded\'');
vm.runInNewContext(calendarTestSource,calendarSandbox);
const calendar=calendarSandbox.window.__calendarTest;
const data=calendar.calendarData();
assert(calendar.icsDate(data.start)==='20261023T213000Z','calendar start is October 23, 2026 at 5:30 PM EDT');
assert(calendar.icsDate(data.end)==='20261026T010000Z','calendar end is October 25, 2026 at 9:00 PM EDT');
assert(data.location==='College of Charleston, Charleston, SC','calendar uses the general weekend location');
assert(data.description.includes('every team builds a project with an AI agent as a teammate'),'calendar uses event description');
const ical=calendar.ics();
['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT','DTSTART:20261023T213000Z','DTEND:20261026T010000Z','SUMMARY:HarborHack 2026','LOCATION:College of Charleston\\, Charleston\\, SC','END:VEVENT','END:VCALENDAR'].forEach(value=>assert(ical.includes(value),`valid calendar contains ${value}`));
assert(!ical.toLowerCase().includes('room'),'calendar output contains no room number');
const locations=sandbox.window.HARBORHACK_2026_CONFIG.schedule.map(item=>`${item.day}:${item.location}`);
assert(locations.includes('Friday:Harbor Walk West'),'Friday location is Harbor Walk West');
assert(locations.includes('Saturday:Harbor Walk East and West'),'Saturday location spans Harbor Walk East and West');
assert(locations.filter(value=>value==='Sunday:Harbor Walk West').length===3,'all Sunday entries use Harbor Walk West');
console.log('HarborHack static tests passed');
