app:
  project: charlestonhacksmatchmaking
  public: public

backends:
  - name: default
    type: genkit
    config:
      framework: react
  - name: matchmaking-functions
    type: functions
    config:
      source: matchmaking-functions
      runtime: nodejs

dataconnect:
  enabled: true
  config:
    connector: matchmaking-system/default
    schema: dataconnect/schema/schema.gql
    queries: dataconnect/connector/queries.gql
    mutations: dataconnect/connector/mutations.gql

firestore:
  rules: firestore.rules
  indexes: firestore.indexes.json

hosting:
  public: public
  ignore:
    - firebase.json
    - "**/.*"
    - "**/node_modules/**"

functions:
  source: matchmaking-functions
  runtime: nodejs
  entry_point: index.js
